# Generated by Django 6.0 on 2025-12-30 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsavelCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Responsável (MA)')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('orcamento_mensal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data (TRANSDATE)')),
                ('descricao_conta', models.CharField(max_length=255)),
                ('txt_detalhe', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('arquivo_origem', models.CharField(help_text='De qual Excel veio esse dado', max_length=255)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='custos.responsavelcusto')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
