# Generated by Django 6.0 on 2026-01-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fornecedor'),
        ),
    ]
