# Generated by Django 6.0 on 2026-01-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custos', '0002_transacao_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_original', models.CharField(max_length=255, unique=True, verbose_name='Nome Original')),
                ('nome_exibicao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome de Exibição')),
                ('exibir', models.BooleanField(default=True, verbose_name='Exibir nas Análises')),
            ],
            options={
                'verbose_name': 'Configuração de Fornecedor',
                'verbose_name_plural': 'Configurações de Fornecedores',
            },
        ),
    ]
