# Generated by Django 6.0 on 2026-01-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custos', '0003_fornecedorconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavelcusto',
            name='nome_exibicao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome de Exibição'),
        ),
    ]
